version: 0.0
os: linux
files:
  - source: /
    destination: /opt/company_prices
permissions:
  - object: /opt/company_prices
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop-server.sh
      timeout: 300
      runas: ubuntu
