spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_CONTAINER:localhost}:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
        jdbc:
          batch_size: 1000
      order_inserts: true

iexapi:
  token: pk_59afd45b2d7044ab8c0379cb39294f93
  url: https://cloud.iexapis.com/stable