apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-prices-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: company-prices-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: company-prices-app
    spec:
      containers:
        - name: company-prices-app-container
          image: 069774556847.dkr.ecr.us-east-1.amazonaws.com/company-prices:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080